AWSTemplateFormatVersion: "2010-09-09"

Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Components
        Parameters:
          - DeployHlsApi
          - DeployIngestMediaLive
          - DeployIngestMediaConvert
      - Label:
          default: Configuration
        Parameters:
          - ApiStackName
    ParameterLabels:
      ApiStackName:
        default: The name of the CloudFormation stack that Deployed the TAMS API
      DeployHlsApi:
        default: Deploy HLS Endpoint?
      DeployIngestMediaLive:
        default: Deploy MediaLive Channel ingest?
      DeployIngestMediaConvert:
        default: Deploy MediaConvert Job ingest?

Parameters:
  ApiStackName:
    Type: String

  DeployHlsApi:
    Type: String
    AllowedValues:
      - "Yes"
      - "No"
    Default: "No"

  DeployIngestMediaLive:
    Type: String
    AllowedValues:
      - "Yes"
      - "No"
    Default: "No"

  DeployIngestMediaConvert:
    Type: String
    AllowedValues:
      - "Yes"
      - "No"
    Default: "No"

Conditions:
  DeployHlsApi: !Equals [!Ref DeployHlsApi, "Yes"]

  DeployIngestMediaLive: !Equals [!Ref DeployIngestMediaLive, "Yes"]

  DeployIngestMediaConvert: !Equals [!Ref DeployIngestMediaConvert, "Yes"]

  DeployApi: !Or [!Condition DeployHlsApi, !Condition DeployIngestMediaLive, !Condition DeployIngestMediaConvert]

  DeployIngest: !Or [!Condition DeployIngestMediaLive, !Condition DeployIngestMediaConvert]

Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Tracing: Active
    Timeout: 30
    MemorySize: 128
    Handler: app.lambda_handler
    Runtime: python3.13
    Architectures:
      - arm64

  Api:
    EndpointConfiguration:
      Type: REGIONAL
    Auth:
      DefaultAuthorizer: AWS_IAM
      AddDefaultAuthorizerToCorsPreflight: False
    TracingEnabled: true
    MethodSettings:
      - ResourcePath: /*
        HttpMethod: '*'
        DataTraceEnabled: True
        LoggingLevel: INFO

Resources:
  OpenIdAuthLayer:
    Type: AWS::Serverless::LayerVersion
    Metadata:
      BuildMethod: python3.13
      BuildArchitecture: arm64
    Properties:
      RetentionPolicy: Delete
      ContentUri: layers/openid-auth
      CompatibleRuntimes:
        - python3.13
      CompatibleArchitectures:
        - arm64
    Condition: DeployApi

  HlsApiStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: components/hls/template.yaml
      Parameters:
        UserPoolId: !ImportValue
          Fn::Sub: ${ApiStackName}-UserPoolId
        ApiEndpoint: !ImportValue
          Fn::Sub: ${ApiStackName}-ApiEndpoint
        UserPoolClientId: !ImportValue
          Fn::Sub: ${ApiStackName}-UserPoolClientId
        TokenUrl: !ImportValue
          Fn::Sub: ${ApiStackName}-TokenUrl
        AuthRoleName: !ImportValue
          Fn::Sub: ${ApiStackName}-AuthRoleName
        OpenIdAuthLayerArn: !Ref OpenIdAuthLayer
    Condition: DeployHlsApi

  IngestStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: components/ingest/template.yaml
      Parameters:
        UserPoolId: !ImportValue
          Fn::Sub: ${ApiStackName}-UserPoolId
        ApiEndpoint: !ImportValue
          Fn::Sub: ${ApiStackName}-ApiEndpoint
        UserPoolClientId: !ImportValue
          Fn::Sub: ${ApiStackName}-UserPoolClientId
        TokenUrl: !ImportValue
          Fn::Sub: ${ApiStackName}-TokenUrl
        AuthRoleName: !ImportValue
          Fn::Sub: ${ApiStackName}-AuthRoleName
        OpenIdAuthLayerArn: !Ref OpenIdAuthLayer
    Condition: DeployIngest

  IngestMediaLiveStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: components/ingest-medialive/template.yaml
      Parameters:
        AuthRoleName: !ImportValue
          Fn::Sub: ${ApiStackName}-AuthRoleName
        SfnFlowsFunctionRole: !GetAtt IngestStack.Outputs.SfnFlowsFunctionRole
        SfnFlowsFunctionArn: !GetAtt IngestStack.Outputs.SfnFlowsFunctionArn
        S3IngestionFunctionRole: !GetAtt IngestStack.Outputs.S3IngestionFunctionRole
        S3IngestionFunctionArn: !GetAtt IngestStack.Outputs.S3IngestionFunctionArn
        ParentStackName: !Ref AWS::StackName
    Condition: DeployIngestMediaLive

  IngestMediaConvertStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: components/ingest-mediaconvert/template.yaml
      Parameters:
        AuthRoleName: !ImportValue
          Fn::Sub: ${ApiStackName}-AuthRoleName
        SfnFlowsFunctionRole: !GetAtt IngestStack.Outputs.SfnFlowsFunctionRole
        SfnFlowsFunctionArn: !GetAtt IngestStack.Outputs.SfnFlowsFunctionArn
        S3IngestionFunctionRole: !GetAtt IngestStack.Outputs.S3IngestionFunctionRole
        S3IngestionFunctionArn: !GetAtt IngestStack.Outputs.S3IngestionFunctionArn
    Condition: DeployIngestMediaConvert

Outputs:
  HlsEndpoint:
    Value: !If
      - DeployHlsApi
      - !GetAtt HlsApiStack.Outputs.ApiEndpoint
      - ""

  MlEndpoint:
    Value: !If
      - DeployIngestMediaLive
      - !GetAtt IngestMediaLiveStack.Outputs.ApiEndpoint
      - ""

  MlStartArn:
    Value: !If
      - DeployIngestMediaLive
      - !GetAtt IngestMediaLiveStack.Outputs.StartArn
      - ""

  MlStopArn:
    Value: !If
      - DeployIngestMediaLive
      - !GetAtt IngestMediaLiveStack.Outputs.StopArn
      - ""

  McEndpoint:
    Value: !If
      - DeployIngestMediaConvert
      - !GetAtt IngestMediaConvertStack.Outputs.ApiEndpoint
      - ""

  MediaConvertBucketName:
    Value: !If
      - DeployIngestMediaConvert
      - !GetAtt IngestMediaConvertStack.Outputs.BucketName
      - ""
