AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  UserPoolId:
    Type: String

  TAMSApiEndpoint:
    Type: String

  UserPoolClientId:
    Type: String

  TokenUrl:
    Type: String

  AuthRole:
    Type: String

  OpenIdAuthLayerArn:
    Type: String

Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Tracing: Active
    Timeout: 30
    MemorySize: 128
    Handler: app.lambda_handler
    Runtime: python3.13
    Architectures:
      - arm64

  Api:
    EndpointConfiguration:
      Type: REGIONAL
    TracingEnabled: true
    MethodSettings:
      - ResourcePath: /*
        HttpMethod: '*'
        DataTraceEnabled: True
        LoggingLevel: INFO

Resources:
  AuthRolePolicyHls:
    Type: AWS::IAM::RolePolicy
    Properties:
      RoleName: !Ref AuthRole
      PolicyName: HlsApi
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - lambda:InvokeFunction
            Resource:
              - !GetAtt ApiHlsFunction.Arn

  Api:
    Type: AWS::Serverless::Api
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
            - W1028
    Properties:
      OpenApiVersion: 3.0.1
      StageName: Prod
      Cors:
        AllowMethods: '''*'''
        AllowHeaders: '''Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'''
        AllowOrigin: '''*'''
      AlwaysDeploy: True

  ApiHlsFunction:
    Type: AWS::Serverless::Function
    Metadata:
      cfn_nag:
        rules_to_suppress:
          - id: W89
            reason: VPC not required
          - id: W92
            reason: ReservedConcurrentExecutions not required
    Properties:
      CodeUri: functions/api-hls/
      Layers:
        - !Sub arn:${AWS::Partition}:lambda:${AWS::Region}:017000801446:layer:AWSLambdaPowertoolsPythonV3-python313-arm64:4
        - !Ref OpenIdAuthLayerArn
      Environment:
        Variables:
          TAMS_ENDPOINT: !Ref TAMSApiEndpoint
          TOKEN_URL: !Ref TokenUrl
          USER_POOL_ID: !Ref UserPoolId
          CLIENT_ID: !Ref UserPoolClientId
          DEFAULT_HLS_SEGMENTS: 150
      Policies:
        - Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Action:
                - cognito-idp:DescribeUserPoolClient
              Resource: !Sub arn:${AWS::Partition}:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/${UserPoolId}
      Events:
        getSourceHls:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /hls/sources/{sourceId}/output.m3u8
            Method: get
        getFlowHls:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /hls/flows/{flowId}/output.m3u8
            Method: get

Outputs:
  ApiEndpoint:
    Value: !Sub https://${Api}.execute-api.${AWS::Region}.amazonaws.com/${Api.Stage}
